[tool.poetry]
name = "era5epw"
version = "0.6.0"
description = "A tool to convert ERA5/ECMWF data to EnergyPlus Weather (EPW) format"
authors = ["Antoine Galataud <antoine@foobot.io>"]
packages = [
    { include = "era5epw" },
]
readme = "README.md"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "~3.12"
numpy = "2.4.4"
pandas = "2.2.3"
xarray = "2026.4.0"
cdsapi = "0.7.7"
netcdf4 = "1.7.4"
plotly = "6.7.0"
zarr = "3.2.1"
dask = "2026.3.0"
requests = "^2.34.0"
aiohttp = "^3.13.5"

[tool.poetry.scripts]
era5epw_download = "era5epw.main:download"
era5epw_visualize = "era5epw.visualize:visualize_cli"
tests = "tests.discover:run"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
