name: tests
concurrency: tests

on: [push]

jobs:
  test:
    name: Test era5epw
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.7.1"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install
        run: |
          poetry install -n

      - name: Run tests
        run: |
          poetry run tests
